<?php
/**
 * This class handles WooCommerce Analytics Categories report.
 *
 * @package Iconic_WSSV
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

/**
 * WooCommerce Analytics Categories report integration class.
 *
 * @since 1.25.0
 */
class Iconic_WSSV_Categories_Report {
	/**
	 * Add action and filters
	 *
	 * @since 1.25.0
	 *
	 * @return void
	 */
	public static function init() {
		add_filter( 'woocommerce_analytics_clauses_join_categories_subquery', [ __CLASS__, 'update_left_join_clause' ], 50, 1 );
	}

	/**
	 * Update the `LEFT JOIN` query clause to include the
	 * column `variation_id`.
	 *
	 * @param array $clauses The query clauses.
	 */
	public static function update_left_join_clause( $clauses ) {
		if ( ! is_array( $clauses ) ) {
			return $clauses;
		}

		if ( ! self::is_categories_report_endpoint() ) {
			return $clauses;
		}

		$left_join = self::get_default_left_join();

		$clauses = array_map(
			function( $clause ) use ( $left_join ) {
				if ( $clause !== $left_join ) {
					return $clause;
				}

				return self::get_left_join_clause_using_variation_id();
			},
			$clauses
		);

		return $clauses;
	}

	/**
	 * Whether the current request is to the categories report endpoint.
	 *
	 * @return boolean
	 */
	protected static function is_categories_report_endpoint() {
		if ( ! defined( 'REST_REQUEST' ) || ! REST_REQUEST ) {
			return false;
		}

		$route = untrailingslashit( $GLOBALS['wp']->query_vars['rest_route'] );

		if ( empty( $route ) ) {
			return false;
		}

		if ( $route !== '/wc-analytics/reports/categories' ) {
			return false;
		}

		return true;
	}

	/**
	 * Get the Order Product Lookup table name.
	 *
	 * @return string
	 */
	protected static function get_order_product_lookup_table_name() {
		global $wpdb;

		$order_product_lookup_table = $wpdb->prefix . 'wc_order_product_lookup';

		return $order_product_lookup_table;
	}

	/**
	 * Mimic the `LEFT JOIN` generated by WooCommerce
	 *
	 * @return string
	 */
	protected static function get_default_left_join() {
		global $wpdb;

		$order_product_lookup_table = self::get_order_product_lookup_table_name();

		$left_join = "LEFT JOIN {$wpdb->term_relationships} ON {$order_product_lookup_table}.product_id = {$wpdb->term_relationships}.object_id";

		return $left_join;
	}

	/**
	 * Get the `LEFT JOIN` using the `variation_id` column.
	 *
	 * @return string
	 */
	protected static function get_left_join_clause_using_variation_id() {
		global $wpdb;

		$order_product_lookup_table = self::get_order_product_lookup_table_name();

		/**
		 * Try to use the `variation_id` if available.
		 *
		 * See:
		 * - https://mariadb.com/kb/en/coalesce/
		 * - https://mariadb.com/kb/en/nullif/
		 */
		$custom_left_join = "LEFT JOIN {$wpdb->term_relationships} ON COALESCE(NULLIF({$order_product_lookup_table}.variation_id, 0), {$order_product_lookup_table}.product_id) = {$wpdb->term_relationships}.object_id";

		return $custom_left_join;
	}
}
